### ISSUE TITLE
rosserial with the ti tm4c123 launchpad. It won't connect 

### ISSUE THREAD

**Issue by blueminerals** [ros-drivers/rosserial#100]
I am trying to use rosserial with the ti tm4c123 launchpad. It won't connect when I do a rosrun rosserial_python serial_node.py /dev/ttyACM0

my ardunio_hardware.h is below
# ifndef ROS_ARDUINO_HARDWARE_H_
# define ROS_ARDUINO_HARDWARE_H_

  #include <Energia.h>  // 
  #include <HardwareSerial.h>

class ArduinoHardware {
  public:
    ArduinoHardware(HardwareSerial\* io , long baud= 57600){
      iostream = io;
      baud_ = baud;
    }
    ArduinoHardware()
    {
      iostream = &Serial;
      baud_ = 57600;
    }
    ArduinoHardware(ArduinoHardware& h){
      this->iostream = iostream;
      this->baud_ = h.baud_;
    }

```
void setBaud(long baud){
  this->baud_= baud;
}  
int getBaud(){return baud_;}

void init(){
  iostream->begin(baud_);
}
int read(){return iostream->read();};
void write(uint8_t* data, int length){
  for(int i=0; i<length; i++)
    iostream->write(data[i]);
}
unsigned long time(){return millis();}
```

  protected:
    HardwareSerial\* iostream;
    long baud_;
};
# endif

**Comment by mikeferguson** [comment]
Does it actually compile? Where is your HardwareSerial defined, what set of underlying libraries are you using? There really isn't enough here to start debugging.

**Comment by blueminerals** [comment]
I am using energia at http://energia.nu/download/. Enclosed is the HardwareSerial files from the energia download. Energia is sort of a clone of the Ardunio IDE for the Ti products. Using the Energia IDE, it does compile. I am not compiling in any other way. If I should , please let me know. I have put ros_lib in the libraries folder under where the sketches are. Thanks for your help.

/\* 
- rosserial Subscriber Example
- Blinks an LED on callback

*/

I am trying to run this program and it compiles in the Energia IDE

//sketch_blink

#include <ros.h>

#include <std_msgs/Empty.h>

ros::NodeHandle  nh;

void messageCb( const std_msgs::Empty& toggle_msg){

  digitalWrite(RED_LED, HIGH);   // blink the led

  delay(1000);

  digitalWrite(RED_LED, LOW);

  delay(1000);

}

ros::Subscriber<std_msgs::Empty> sub("toggle_led", &messageCb );

void setup()

{ 

  pinMode(RED_LED, OUTPUT);

  nh.initNode();

  nh.subscribe(sub);

}

void loop()

{  

  nh.spinOnce();

  delay(1);

}

Then I run this:

qmi@ubuntu:/dev$ rosrun rosserial_python serial_node.py /dev/ttyACM0

[INFO] [WallTime: 1392985717.959284] ROS Serial Python Node

[INFO] [WallTime: 1392985717.985203] Connecting to /dev/ttyACM0 at 9600 baud

[ERROR] [WallTime: 1392985735.116228] Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

[ERROR] [WallTime: 1392986335.570003] Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

I controlled-C at this point

Traceback (most recent call last):

  File "/opt/ros/hydro/lib/rosserial_python/serial_node.py", line 82, in <module>

```
client.run()
```

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 387, in run

```
flag[0]  = self.port.read(1)
```

  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 456, in read

```
raise SerialException('device reports readiness to read but returned no data (device disconnected?)')
```

serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected?)

**Comment by bmagyar** [comment]
Hey @blueminerals ,

How urgent is this for you? 

I have a fully working implementation of rosserial on the Tiva both using Energia and the advanced way using Code Composer Studio with only the TivaWare libraries.
Be warned! These videos may be less professional than what you expect ;)
https://www.youtube.com/watch?v=I4dPV7aJafk
https://www.youtube.com/watch?v=--hj8MRKHUM

I am planning to release the package soon, since I see great potential in this board. Any ideas where it should go? Here, along with the rest of the rosserial stuff, or should I release it from me own repo?

**Comment by PaulBouchier** [comment]
Just a quick observation: your arduino_hardware.h has baud rate set to default to 57600, which is the default, but your rosserial_python prints that it's connecting at 9600. Check the baud rates on the wire. It looks like it just can't start talking.

**Comment by blueminerals** [comment]
It is not urgent at all, because we couldn’t get it to work, we went to a different approach. I would suggest github for the repo. Thanks for your work. The Launchpads are cheap and have quadrature  decoders. They have come out with  the 129 with is 120 mhz and has Ethernet.
