### ISSUE TITLE
rosserial unable to sync (Arduino Micro)

### ISSUE THREAD

**Issue by Danielvr** [ros-drivers/rosserial#122]
I'm trying to get the Arduino Micro getting synced with Rosserial Python.
I already have tried several things. Try it with groovy, hydro and a reinstall of Ubuntu didn't helped. 
De program I am running on the Arduino is the Hello World demo program and the command that I run to start it to connect it with ROS is:
rosrun rosserial_python serial_node.py /dev/ttyACM0

```
[INFO] [WallTime: 1400597906.314950] ROS Serial Python Node
[INFO] [WallTime: 1400597906.326865] Connecting to /dev/ttyACM0 at 57600 baud
[ERROR] [WallTime: 1400597923.435702] Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```

When I disconnect the arduino I get this.

```
Traceback (most recent call last):
  File "/home/uaslab/groovy_workspace/install/lib/rosserial_python/serial_node.py", line 82, in <module>
    client.run()
  File "/home/uaslab/groovy_workspace/install/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 474, in run
    self.requestTopics()
  File "/home/uaslab/groovy_workspace/install/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 373, in requestTopics
    self.port.flushInput()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 497, in flushInput
    termios.tcflush(self.fd, TERMIOS.TCIFLUSH)
termios.error: (5, 'Input/output error')
```

So the arduino is conected. What is my problem and how can I solve it. I can't find the answer online.

**Comment by Danielvr** [comment]
I have fixed it. What you need to do is.

The "Hello World" example seems to be working fine. The only change you must to your Arduino code on Micro or just the normal one, I only have a Micro is to add

`#define USE_USBCON`

just before

`#include <ros.h>`

That's it
