### ISSUE TITLE
Unable to build ROSSerial with catkin: 'module' object has no attribute 'Interpreter'

### ISSUE THREAD

**Issue by chrisspen** [ros-drivers/rosserial#204]
I'm attempting to setup an Arduino IDE so it can include ROS code, following the [ROS serial](http://wiki.ros.org/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup) tutorial, but the `catkin_make` fails:

```
sudo apt-get install ros-indigo-rosserial-arduino ros-indigo-rosserial
virtualenv .env
. .env/bin/activate
pip install catkin_pkg em
mkdir src
cd src
git clone https://github.com/ros-drivers/rosserial.git
cd ..
catkin_make
```

with the following output:

```
Base path: /home/myuser/git/myproject
Source space: /home/myuser/git/myproject/src
Build space: /home/myuser/git/myproject/build
Devel space: /home/myuser/git/myproject/devel
Install space: /home/myuser/git/myproject/install
####
#### Running command: "make cmake_check_build_system" in "/home/myuser/git/myproject/build"
####
####
#### Running command: "make -j4 -l4" in "/home/myuser/git/myproject/build"
####
[  0%] Built target _rosserial_mbed_generate_messages_check_deps_Adc
[  0%] Built target _rosserial_mbed_generate_messages_check_deps_Test
[  0%] [  0%] Built target _rosserial_arduino_generate_messages_check_deps_Test
Built target _rosserial_arduino_generate_messages_check_deps_Adc
[  0%] Built target _rosserial_msgs_generate_messages_check_deps_Log
[  0%] Built target _rosserial_msgs_generate_messages_check_deps_RequestParam
[  0%] [  5%] [  5%] Built target _rosserial_msgs_generate_messages_check_deps_RequestMessageInfo
Built target _rosserial_msgs_generate_messages_check_deps_TopicInfo
Built target rosserial_arduino_generate_messages_lisp
[ 17%] Built target rosserial_arduino_generate_messages_py
[ 22%] Built target rosserial_arduino_generate_messages_cpp
[ 28%] [ 28%] Built target rosserial_mbed_generate_messages_lisp
Built target _rosserial_msgs_generate_messages_check_deps_RequestServiceInfo
[ 40%] Scanning dependencies of target rosserial_arduino_generate_messages
Built target rosserial_mbed_generate_messages_py
[ 45%] Built target rosserial_mbed_generate_messages_cpp
[ 45%] Built target rosserial_arduino_generate_messages
[ 65%] Built target rosserial_msgs_generate_messages_py
[ 80%] [ 82%] [ 85%] Built target rosserial_msgs_generate_messages_lisp
Generating C++ code from rosserial_msgs/RequestServiceInfo.srv
[ 85%] Generating C++ code from rosserial_msgs/RequestMessageInfo.srv
Built target rosserial_mbed_generate_messages
Traceback (most recent call last):
  File "/opt/ros/indigo/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    srv_template_map)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 212, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 155, in generate_from_file
    _generate_srv_from_file(input_file, output_dir, template_dir, search_path, package_name, srv_template_dict, msg_template_dict)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 114, in _generate_srv_from_file
    search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 76, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'Interpreter'
make[2]: *** [/home/myuser/git/myproject/devel/include/rosserial_msgs/RequestServiceInfo.h] Error 1
make[2]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/indigo/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    srv_template_map)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 212, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 155, in generate_from_file
    _generate_srv_from_file(input_file, output_dir, template_dir, search_path, package_name, srv_template_dict, msg_template_dict)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 114, in _generate_srv_from_file
    search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/template_tools.py", line 76, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'Interpreter'
make[2]: *** [/home/myuser/git/myproject/devel/include/rosserial_msgs/RequestMessageInfo.h] Error 1
make[1]: *** [rosserial/rosserial_msgs/CMakeFiles/rosserial_msgs_generate_messages_cpp.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
```

Have I misconfigured something, or is this a bug?

**Comment by mikepurvis** [comment]
Looks like you're ending up with [em](https://pypi.python.org/pypi/em/) rather than [empy](https://pypi.python.org/pypi/EmPy).

Normally this isn't an issue if you've otherwise installed ROS on your platform, as empy is used extensively by catkin itself and the message generators, so you already have it all set up.
