### ISSUE TITLE
error with rosserial_python node

### ISSUE THREAD

**Issue by pedroosorio** [ros-drivers/rosserial#256]
Hi guys. I keep getting this error 

`traceback (most recent call last):
 File "/opt/ros/kinetic/lib/rosserial_python/serial_node.py", line 85, in <module>
 client.run()
 File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 503, in run
 self.requestTopics()
 File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 389, in requestTopics
 self.port.flushInput()
 File "/home/lar/.local/lib/python2.7/site-packages/serial/serialutil.py", line 512, in flushInput
 self.reset_input_buffer()
 File "/home/lar/.local/lib/python2.7/site-packages/serial/serialposix.py", line 556, in reset_input_buffer
 termios.tcflush(self.fd, termios.TCIFLUSH)
 termios.error: (5, 'Input/output error')
 [ERROR] [1480067138.962050]: bad callback: <bound method Subscriber.callback of                    <rosserial_python.SerialClient.Subscriber instance at 0x7fdf8e465710>>
 Traceback (most recent call last):
   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
  cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 137, in callback
  self.parent.send(self.id, data_buffer.getvalue())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 698, in send
  self.port.write(data)
  File "/home/lar/.local/lib/python2.7/site-packages/serial/serialposix.py", line 537, in write
  raise SerialException('write failed: {}'.format(v))
  SerialException: write failed: [Errno 5] Input/output error
`

Using rosserial_python serial_node.py, connected to an Arduino Mega2560, 57600 baud, ROS Kinetic, Ubuntu 16.04 (Server edition). If i start publishing data (which the arduino subscribes), after a while, this error happens.

Thanks

**Comment by AlexisTM** [comment]
This looks like a USB disconnection, like #195, you should try updating your kernel.
