### ISSUE TITLE
Undefined message on error #195

### ISSUE THREAD

**Issue by AlexisTM** [ros-drivers/rosserial#265]
As the issue #195 pointed out, there could be this error : 

```
$ rosrun rosserial_python serial_node.py _port:=/dev/ttyUSB0 _baud:=115200
[INFO] [WallTime: 1444743760.324098] ROS Serial Python Node
[INFO] [WallTime: 1444743760.331972] Connecting to /dev/ttyUSB0 at 115200 baud
[WARN] [WallTime: 1444743762.445800] Serial Port read failure: device reports readiness to read but returned no data (device disconnected?)
[INFO] [WallTime: 1444743762.446595] Packet Failed :  Failed to read msg data
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/rosserial_python/serial_node.py", line 82, in <module>
    client.run()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 475, in run
    rospy.loginfo("msg len is %d",len(msg))
UnboundLocalError: local variable 'msg' referenced before assignment
```

Indeed, `msg` comes from `msg = self.tryRead(msg_length)` while `self.tryRead` do not return anything on error. Therefore, `msg` is undefined when doing the `except IOError:`

[Reading code](https://github.com/ros-drivers/rosserial/blob/jade-devel/rosserial_python/src/rosserial_python/SerialClient.py#L478-L484) : 

```python
                try:
                    msg = self.tryRead(msg_length)
                except IOError:
                    self.sendDiagnostics(diagnostic_msgs.msg.DiagnosticStatus.ERROR, "Packet Failed : Failed to read msg data")
                    rospy.loginfo("Packet Failed :  Failed to read msg data")
                    rospy.loginfo("msg len is %d",len(msg))
                    raise
```

[def tryRead(self, length):](https://github.com/ros-drivers/rosserial/blob/jade-devel/rosserial_python/src/rosserial_python/SerialClient.py#L401-L422)

```python
    def tryRead(self, length):
        try:
            read_start = time.time()
            read_current = read_start
            bytes_remaining = length
            result = bytearray()
            while bytes_remaining != 0 and read_current - read_start < self.timeout:
                received = self.port.read(bytes_remaining)
                if len(received) != 0:
                    result.extend(received)
                    bytes_remaining -= len(received)
                read_current = time.time()

            if bytes_remaining != 0:
                rospy.logwarn("Serial Port read returned short (expected %d bytes, received %d instead)."
                              % (length, length - bytes_remaining))
                raise IOError()

            return bytes(result)
        except Exception as e:
            rospy.logwarn("Serial Port read failure: %s", e)
            raise IOError()
```

**Comment by AlexisTM** [comment]
Outdated.
