### ISSUE TITLE
ros-serial error with arduino/teensy

### ISSUE THREAD

**Issue by operl** [ros-drivers/rosserial#396]
This has been working but now I when I run it I eventually get his error

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/rosserial_python/serial_node.py", line 89, in <module>
    client.run()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 515, in run
    self.requestTopics()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 397, in requestTopics
    self.port.flushInput()
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 532, in flushInput
    self.reset_input_buffer()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 566, in reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)

then when I try to relaunch my launch file it says it can't connect to /dev/ttyACM0 anymore. I reset it and I have to do this dance all over again

Any help/suggestions would be appreciated

**Comment by mattions** [comment]
I'm experiencing the same problem.

My error looks exactly the same:

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/rosserial_python/serial_node.py", line 89, in <module>
    client.run()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 515, in run
    self.requestTopics()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 397, in requestTopics
    self.port.flushInput()
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 532, in flushInput
    self.reset_input_buffer()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 566, in reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
[rosserial-3] process has died [pid 3351, exit code 1, cmd /opt/ros/kinetic/lib/rosserial_python/serial_node.py /dev/ttyACM0 __name:=rosserial __log:=/home/mattions/.ros/log/7e9c0b0a-d43e-11e8-b077-b827ebba6439/rosserial-3.log].
log file: /home/mattions/.ros/log/7e9c0b0a-d43e-11e8-b077-b827ebba6439/rosserial-3*.log
```

this is my log file: 
```
[rospy.client][INFO] 2018-10-20 09:02:34,863: init_node, name[/rosserial], pid[3351]
[xmlrpc][INFO] 2018-10-20 09:02:34,864: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-10-20 09:02:34,865: Started XML-RPC server [http://raspy:36487/]
[rospy.init][INFO] 2018-10-20 09:02:34,866: ROS Slave URI: [http://raspy:36487/]
[rospy.impl.masterslave][INFO] 2018-10-20 09:02:34,867: _ready: http://raspy:36487/
[xmlrpc][INFO] 2018-10-20 09:02:34,868: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-10-20 09:02:34,870: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-10-20 09:02:34,967: registered with master
[rospy.rosout][INFO] 2018-10-20 09:02:34,968: initializing /rosout core topic
[rospy.rosout][INFO] 2018-10-20 09:02:34,982: connected to core topic /rosout
[rospy.simtime][INFO] 2018-10-20 09:02:34,990: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2018-10-20 09:02:35,001: ROS Serial Python Node
[rosout][INFO] 2018-10-20 09:02:35,020: Connecting to /dev/ttyACM0 at 57600 baud
[rospy.internal][INFO] 2018-10-20 09:02:35,297: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-10-20 09:02:37,162: Note: publish buffer size is 200 bytes
[rosout][INFO] 2018-10-20 09:02:37,164: Setup publisher on soil_sensor [gardenio_msgs/SoilSensor]
[rosout][INFO] 2018-10-20 09:02:37,185: Note: subscribe buffer size is 200 bytes
[rosout][INFO] 2018-10-20 09:02:37,188: Setup subscriber on acquire_soil_humidity [std_msgs/Empty]
[rospy.internal][INFO] 2018-10-20 09:02:37,204: topic[/acquire_soil_humidity] adding connection to [http://raspy:46299/], count 0
[rosout][INFO] 2018-10-20 09:02:37,220: Setup subscriber on pump [std_msgs/UInt16]
[rospy.internal][INFO] 2018-10-20 09:02:37,250: topic[/soil_sensor] adding connection to [/gardenio_connect], count 0
[rosout][INFO] 2018-10-20 09:02:37,253: Setup subscriber on water_command [gardenio_msgs/SoilSensor]
[rospy.internal][INFO] 2018-10-20 09:02:45,250: topic[/acquire_soil_humidity] adding connection to [http://raspy:39677/], count 1
[rospy.internal][ERROR] 2018-10-20 09:02:48,241: Unable to initiate TCP/IP socket to raspy:38843 (http://raspy:39677/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2018-10-20 09:02:49,244: Unknown error initiating TCP/IP socket to raspy:38843 (http://raspy:39677/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

I can actually relaunch the rosmaster and rosserial without the need to do the reset on the arduino as the case @operl 

It seems that other people have the same type of issue: #256 and the suggestion was to upgrade the kernel due the problem being related to how the kernel was handling the USB.

I'm running a ubuntu mate 16.04.5 on the rasberrypi, and the current kernel is 
```
Linux raspy 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l armv7l armv7l GNU/Linux
```
which is a lot newer than the one where the problem was first spotted, so I'm not sure this is relevant anymore.

Anyone managed to dig further?
