### ISSUE TITLE
ROS Arduino Leo on Udoo V8 Bolt communication issue with ROS Serial

### ISSUE THREAD

**Issue by akrolic** [ros-drivers/rosserial#467]
We have ubuntu 18.04 , ROS Melodic and python 2.7 
We are have uploaded the helloworld example sketch to the arduino leo board and are not able to see the chatter topic come up in the rostopic list. We are able to see the rosnode /serial_node but do not see any subscribers to this node. 
>$rosnode info /serial_node 
--------------------------------------------------------------------------------
Node [/serial_node]
Publications: 
 * /diagnostics [diagnostic_msgs/DiagnosticArray]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: None

Services: 
 * /serial_node/get_loggers
 * /serial_node/set_logger_level

contacting node http://lab-C40:33913/ ...
Pid: 5114
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS

> [INFO] [1582916715.527676]: Requesting topics...
[ERROR] [1582916722.642601]: Write timeout: Write timeout
[ERROR] [1582916730.529527]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
[INFO] [1582916730.531347]: Requesting topics...
[ERROR] [1582916733.653852]: Write timeout: Write timeout
^C[INFO] [1582916744.001793]: Send tx stop request
[WARN] [1582916744.003724]: Unexpected Error.<type 'exceptions.SystemExit'>
^CTraceback (most recent call last):
  File "/home/lab/rosserial_ws/src/rosserial/rosserial_python/nodes/serial_node.py", line 101, in <module>
    sleep(1.0)
  File "/home/lab/rosserial_ws/src/rosserial/rosserial_python/src/rosserial_python/SerialClient.py", line 418, in txStopRequest
    self.port.flushInput()
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 584, in flushInput
    self.reset_input_buffer()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 594, in reset_input_buffer
    raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open

Anyone experience a similar issue or have any advice on how to fix this?
Thanks!

**Comment by himadrir** [comment]
add #define USE_USBCON before #include <ros.h>. AFAIK the udoo board has a leonardo so this line is required
