### ISSUE TITLE
rosserial_python Noetic problens

### ISSUE THREAD

**Issue by AppliedRobotics** [ros-drivers/rosserial#507]
I tried to run rosserial_python with ros noetic and rp3b+ and get this errors.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/ros_package_rp_worldskills/src/AR_TB4WD/rosserial/rosserial_python/src/rosserial_python/SerialClient.py", line 789, in processWriteQueue
    self._write(data)
  File "/home/ubuntu/ros_package_rp_worldskills/src/AR_TB4WD/rosserial/rosserial_python/src/rosserial_python/SerialClient.py", line 752, in _write
    self.port.write(data)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 532, in write
    d = to_bytes(data)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: 'ÿþ\x00\x00ÿ\x00\x00ÿ'
[ERROR] [1597239707.248445]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

**Comment by mikepurvis** [comment]
The Python 3 updates have now finally merged. Please give the current `noetic-devel` branch a try and open new issues for any problems you encounter.
