### ISSUE TITLE
rviz fails in rosserial_mbed make_libraries.py

### ISSUE THREAD

**Issue by marcelbrucker** [ros-drivers/rosserial#538]
I followed the [tutorial](http://wiki.ros.org/rosserial_mbed/Tutorials/rosserial_mbed%20Setup) and when executing `rosrun rosserial_mbed make_libraries.py ~/ros/lib` in the 3rd step I encountered this issue with `rviz`:

> Exporting rosserial_msgs
> 
>   Messages:
>     Log,TopicInfo,
> 
>   Services:
>     RequestParam,
> 
> Exporting rviz
> 
>   Services:
>     SendFilePath,[rviz]: Unable to build messages: PyCapsule_GetPointer called with incorrect name
> 
> Traceback (most recent call last):
>   File "/home/marcel/catkin_ws/src/rosserial/rosserial_client/src/rosserial_client/make_library.py", line 561, in rosserial_generate
>     MakeLibrary(p, path, rospack)
>   File "/home/marcel/catkin_ws/src/rosserial/rosserial_client/src/rosserial_client/make_library.py", line 531, in MakeLibrary
>     srv_class = roslib.message.get_service_class(package+'/'+f[0:-4])
>   File "/opt/ros/noetic/lib/python3/dist-packages/roslib/message.py", line 124, in get_service_class
>     cls = genpy.message.get_service_class(service_type, reload_on_error=reload_on_error)
>   File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 713, in get_service_class
>     cls = _get_message_or_service_class('srv', service_type, reload_on_error=reload_on_error)
>   File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 635, in _get_message_or_service_class
>     pypkg = __import__('%s.%s' % (package, type_str))
>   File "/opt/ros/noetic/lib/python3/dist-packages/rviz/__init__.py", line 25, in <module>
>     from . import librviz_sip as bindings
> ValueError: PyCapsule_GetPointer called with incorrect name
> 
> Exporting sensor_msgs
> 
>   Messages:
>     PointCloud,Image,JoyFeedback,MagneticField,BatteryState,Range,Temperature,LaserScan,Joy,FluidPressure,PointField,MultiEchoLaserScan,JointState,RelativeHumidity,CameraInfo,NavSatFix,Imu,MultiDOFJointState,PointCloud2,TimeReference,ChannelFloat32,JoyFeedbackArray,RegionOfInterest,Illuminance,LaserEcho,CompressedImage,NavSatStatus,
> 
>   Services:
>     SetCameraInfo,

I couldn't find a solution to solve it and I'm not sure if it is the reason I cannot successfully run any provided code examples.

**Comment by ng572** [comment]
similar issue here
```
*** Warning, failed to generate libraries for the following packages: ***
    rviz (PyCapsule_GetPointer called with incorrect name)
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/rosserial_arduino/make_libraries.py", line 91, in <module>
    rosserial_generate(rospack, output_path, ROS_TO_EMBEDDED_TYPES)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_client/make_library.py", line 571, in rosserial_generate
    raise Exception("Failed to generate libraries for: " + str(failed))
Exception: Failed to generate libraries for: ['rviz (PyCapsule_GetPointer called with incorrect name)']
```
