### ISSUE TITLE
ImportError: cannot import name 'TopicInfo' from 'rosserial_msgs.msg' (unknown location)

### ISSUE THREAD

**Issue by ismailabouzeidx** [ros-drivers/rosserial#590]
along with the first error I'm facing the following errors:
Traceback (most recent call last):
  File "/home/ismail/catkin_ws/devel/lib/rosserial_arduino/serial_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/ismail/catkin_ws/src/rosserial/rosserial_arduino/nodes/serial_node.py", line 37, in <module>
    from rosserial_arduino import SerialClient
  File "/home/ismail/catkin_ws/devel/lib/python3/dist-packages/rosserial_arduino/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/home/ismail/catkin_ws/src/rosserial/rosserial_arduino/src/rosserial_arduino/SerialClient.py", line 43, in <module>
    from rosserial_python import SerialClient as _SerialClient
  File "/home/ismail/catkin_ws/devel/lib/python3/dist-packages/rosserial_python/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/home/ismail/catkin_ws/src/rosserial/rosserial_python/src/rosserial_python/SerialClient.py", line 53, in <module>
    from rosserial_msgs.msg import TopicInfo, Log
ImportError: cannot import name 'TopicInfo' from 'rosserial_msgs.msg' (unknown location)

Any ideas? Thanks!

**Comment by rda11** [comment]
same error for me! did you sort this out?
